language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install

script: 
  - mkdir -p build/logs
  - composer run-script test
  - composer run-script lint

after_success:
  - travis_retry php vendor/bin/php-coveralls

cache:
  directories:
    - "$HOME/.composer/cache/files"